# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #999CA4

background #22272C
foreground #B5B7BB

color0 #3E444B
color1 #7097BC
color2 #8A8D98
color3 #7E8FA8
color4 #60728D
color5 #787B84
color6 #5C6069
color7 #8D9096
color8 #636469
color9 #6891B8
color10 #8A8D98
color11 #7E8FA8
color12 #60728D
color13 #787B84
color14 #5C6069
color15 #8D9096

mark1_foreground #4A5369
mark2_foreground #717D96
mark3_foreground #4A5369
