# colors for fuzzel application launcher
# You can use this template by adding the following to wallust.toml:
# fuzzel = { template = "fuzzel.ini", target = "~/.config/fuzzel/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/fuzzel/colors.ini


[colors]
background=#22272Cff
text=#B5B7BBff
prompt=#3E444Bff
placeholder=#7097BCff
input=#8A8D98ff
match=#7E8FA8ff
selection=#60728Dff
selection-text=#787B84ff
selection-match=#5C6069ff
counter=#8D9096ff
border=#636469ff
