# colors for fuzzel application launcher
# You can use this template by adding the following to wallust.toml:
# fuzzel = { template = "fuzzel.ini", target = "~/.config/fuzzel/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/fuzzel/colors.ini


[colors]
background=#361F1Aff
text=#C4CACEff
prompt=#583A34ff
placeholder=#F75847ff
input=#994146ff
match=#9A7683ff
selection=#60454Fff
selection-text=#425D63ff
selection-match=#7C8A92ff
counter=#A2ABB0ff
border=#71787Bff
