# Hyprland with colors from wallust
# The
# You can use this template by adding the following to wallust.toml:
# hypr = { src = "hyprland-colors.conf", dst = "~/.config/hypr/colors.conf" }
# and then on hyprland.conf:
# source = ~/.config/hypr/colors.conf

general {
    # Here we use `saturate` filter to have more vibrant colors,
    # not matter the scheme, since the border should seek the attention
    col.active_border = rgb(F7321C) rgb(991A21) rgb(9A2F56) rgb(601C35) rgb(1A5663) rgb(326F92)
    # color0 is almost the same as the background color,
    # by putting ee as the alpha, it makes it 100% transparent
    col.inactive_border = rgba(583A34ee)
}
